apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: ubuntu-python3-app
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        #imagePullPolicy: Never
        env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
        ports:
        - containerPort: 8000
        readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
        livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
