apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 2
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: ubuntu-python3-app
        image: docker.io/rhonakia/ubuntu_python3:latest
        env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
  #      readinessProbe:
   #         httpGet:
    #          path: /healthz
     #         port: 8000
      #  livenessProbe:
       #     httpGet:
        #      path: /healthz
         #     port: 8000
